services:
  yolo-worker-1:
    build:
      context: ./Door-bell-backend/Python-engine
      args:
        CUDA_BASE: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  yolo-worker-2:
    build:
      context: ./Door-bell-backend/Python-engine
      args:
        CUDA_BASE: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  yolo-worker-3:
    build:
      context: ./Door-bell-backend/Python-engine
      args:
        CUDA_BASE: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
